name: Build Docker Images

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Setup QEMU for Docker Buildx
        uses: docker/setup-qemu-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/nekolsd/sing-box
          tags: |
            type=raw,value=${{ github.ref_name }}
            type=raw,value=latest
      
      - name: Build and release Docker images
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          target: dist
          context: .
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
          tags: ${{ steps.metadata.outputs.tags }}
          push: true
          provenance: false